INSERT INTO futbolistas (nombre, apellidos, nacionalidad, equipo, posicion, edad) VALUES
('Lionel', 'Messi', 'Argentina', 'Paris Saint-Germain', 'Delantero', 35),
('Cristiano', 'Ronaldo', 'Portugal', 'Manchester United', 'Delantero', 38),
('Neymar', 'da Silva Santos Júnior', 'Brasil', 'Paris Saint-Germain', 'Delantero', 30),
('Kylian', 'Mbappé', 'Francia', 'Paris Saint-Germain', 'Delantero', 24),
('Robert', 'Lewandowski', 'Polonia', 'Bayern Munich', 'Delantero', 33),
('Kevin', 'De Bruyne', 'Bélgica', 'Manchester City', 'Centrocampista', 30),
('Erling', 'Haaland', 'Noruega', 'Borussia Dortmund', 'Delantero', 21),
('Karim', 'Benzema', 'Francia', 'Real Madrid', 'Delantero', 34),
('Mohamed', 'Salah', 'Egipto', 'Liverpool', 'Delantero', 30),
('Sadio', 'Mané', 'Senegal', 'Liverpool', 'Delantero', 29),
('Virgil', 'van Dijk', 'Países Bajos', 'Liverpool', 'Defensa', 31),
('Harry', 'Kane', 'Inglaterra', 'Tottenham Hotspur', 'Delantero', 29),
('Bruno', 'Fernandes', 'Portugal', 'Manchester United', 'Centrocampista', 28),
('Luka', 'Modrić', 'Croacia', 'Real Madrid', 'Centrocampista', 36),
('Jan', 'Oblak', 'Eslovenia', 'Atlético de Madrid', 'Portero', 30),
('Jadon', 'Sancho', 'Inglaterra', 'Manchester United', 'Delantero', 22),
('Trent', 'Alexander-Arnold', 'Inglaterra', 'Liverpool', 'Defensa', 24),
('Marcus', 'Rashford', 'Inglaterra', 'Manchester United', 'Delantero', 25),
('Frenkie', 'de Jong', 'Países Bajos', 'Barcelona', 'Centrocampista', 25),
('Raheem', 'Sterling', 'Inglaterra', 'Manchester City', 'Delantero', 28),
('Gianluigi', 'Donnarumma', 'Italia', 'Paris Saint-Germain', 'Portero', 24),
('Romelu', 'Lukaku', 'Bélgica', 'Chelsea', 'Delantero', 29),
('Thiago', 'Alcântara', 'España', 'Liverpool', 'Centrocampista', 31),
('Alphonso', 'Davies', 'Canadá', 'Bayern Munich', 'Defensa', 21),
('Joshua', 'Kimmich', 'Alemania', 'Bayern Munich', 'Centrocampista', 27),
('Ederson', 'Santana de Moraes', 'Brasil', 'Manchester City', 'Portero', 29),
('Marquinhos', 'Corrêa', 'Brasil', 'Paris Saint-Germain', 'Defensa', 28),
('Andrew', 'Robertson', 'Escocia', 'Liverpool', 'Defensa', 29),
('Phil', 'Foden', 'Inglaterra', 'Manchester City', 'Centrocampista', 22),
('Casemiro', 'de Souza', 'Brasil', 'Real Madrid', 'Centrocampista', 30),
('Eden', 'Hazard', 'Bélgica', 'Real Madrid', 'Delantero', 31),
('Luis', 'Suárez', 'Uruguay', 'Atlético de Madrid', 'Delantero', 35),
('Marco', 'Verratti', 'Italia', 'Paris Saint-Germain', 'Centrocampista', 29),
('Aymeric', 'Laporte', 'España', 'Manchester City', 'Defensa', 28),
('Paul', 'Pogba', 'Francia', 'Manchester United', 'Centrocampista', 30),
('Thibaut', 'Courtois', 'Bélgica', 'Real Madrid', 'Portero', 30),
('Jorginho', 'Frello Filho', 'Italia', 'Chelsea', 'Centrocampista', 30),
('Antoine', 'Griezmann', 'Francia', 'Atlético de Madrid', 'Delantero', 31),
('João', 'Félix', 'Portugal', 'Atlético de Madrid', 'Delantero', 23),
('Kai', 'Havertz', 'Alemania', 'Chelsea', 'Centrocampista', 23),
('David', 'Alaba', 'Austria', 'Real Madrid', 'Defensa', 30),
('Rúben', 'Dias', 'Portugal', 'Manchester City', 'Defensa', 26),
('César', 'Azpilicueta', 'España', 'Chelsea', 'Defensa', 33),
('Bernardo', 'Silva', 'Portugal', 'Manchester City', 'Centrocampista', 28),
('Vinícius', 'Júnior', 'Brasil', 'Real Madrid', 'Delantero', 22),
('Yann', 'Sommer', 'Suiza', 'Borussia Mönchengladbach', 'Portero', 34),
('Wilfred', 'Ndidi', 'Nigeria', 'Leicester City', 'Centrocampista', 25),
('Jack', 'Grealish', 'Inglaterra', 'Manchester City', 'Centrocampista', 26),
('Declan', 'Rice', 'Inglaterra', 'West Ham United', 'Centrocampista', 24),
('Pedri', 'González', 'España', 'Barcelona', 'Centrocampista', 20),
('Kasper', 'Schmeichel', 'Dinamarca', 'Leicester City', 'Portero', 35),
('Kalidou', 'Koulibaly', 'Senegal', 'Napoli', 'Defensa', 31),
('Hakim', 'Ziyech', 'Marruecos', 'Chelsea', 'Centrocampista', 29),
('Sergej', 'Milinković-Savić', 'Serbia', 'Lazio', 'Centrocampista', 28);
